# Use official Node.js image as base 
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy application source code
COPY . .

VOLUME ["/app/uploads"]
# Expose port (change if your server uses a different port)
EXPOSE 3020

# Start the server (usando npm run start:docker para evitar preload de dotenv)
CMD ["npm", "run", "start:docker"]